
# coding=utf-8

from go.util import DotDict
from card.core.enum import Vip

class MoneyBagType(object):
    MONKEY_FIFTY_RMB_BAGS = 1
    NEWYEAR_SIX_RMB_BAGS = 2

PLAYER = DotDict({
    'before_start':True,
    'needUpdate':0,
    'update_url':'http://',
    'charge_limit': 0,
    "enable_super_package": [],#["toutiao_cpc_v210_001", 'toutiao_cpc_v210_002', 'toutiao_cpc_v210_003', 'toutiao_cpc_v201_007', 'toutiao_cpc_v201_005'],
    'fruit_close':[{'channel':'ss_toutiao_cpc_v201','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_001','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_002','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_003','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_004','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_005','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_006','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_007','version':'2.0.1'},
                   {'channel':'lenovo_duowan', 'version':'2.0.0'},
                   {'channel':'lenovo_duowan', 'version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_008', 'version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_009', 'version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_010', 'version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_011', 'version':'2.0.1'},
                   {'channel':'toutiao_cpc_v210_001', 'version':'2.1.0'},
                   {'channel':'toutiao_cpc_v210_002', 'version':'2.1.0'},
                   {'channel':'toutiao_cpc_v210_003', 'version':'2.1.0'},
		   {'channel':'toutiao_cpc_v201_007', 'version':'2.1.0'},
		   {'channel':'toutiao_cpc_v201_005', 'version':'2.1.0'},
		   #{'channel':'lianyun_hzxly', 'version':'2.1.0'},
                   {'channel':'sj_toutiao_cpc_v201_001', 'version':'2.0.1'},],
    'turncard_close':[{'channel':'ss_toutiao_cpc_v201','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_001','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_002','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_003','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_004','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_005','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_006','version':'2.0.1'},
                   {'channel':'toutiao_cpc_v201_007','version':'2.0.1'},
                   {'channel':'lenovo_duowan', 'version':'2.0.0'},
                   {'channel':'lenovo_duowan', 'version':'2.0.1'},
		   ],
    'three_close':[
		{'channel':'lenovo_duowan', 'version':'2.0.0'},
		{'channel':'lenovo_duowan', 'version':'2.0.1'},
		  ],
    'all_chat':True,
    'vip_chat':True,
    'start_time':0,
    'end_time':540,
    'vip_chat_days':[6,7],
    'identify':False,
    'bank_commission':0.01,
    'idiom_aes_key':"a281ac23d75d84df55ff84b13d2ae1ce",
    'idiom_identify_award':1000,
    'nick_name_hash_key':"NICK_NAME:HASH:KEY",
    'exclude_nick_names': [u"新人",],
    'abmormal_player_set':"Daily:no_daily_award_ids:Set",
    'vip_bag_msg':u"您领取了{0}大礼包！",
    'max_bank_commission':500000,
    'max_cat_weight':6000,
    'vip_criterials': [6, 88, 388, 888, 3888],
    'reset_password': DotDict({
        "token_expire_time": 86400,
        "forget_password_interval":60,
        "last_forget_password_key": "BANK:FORGET:PASSWORD:HASH",
        "url_prefix": "http://120.27.103.99/three/player/bank_password/reset/?token={0}",
        "token_key_prefix": "BANK:FORGET:PASSWORD:{0}:{1}",
        'subject': u'全民豹子王银行密码重置! ',
        'context': u'''您好, 感谢您对全民豹子王的热爱, 请尽快点击如下链接重置银行密码!\n 重置银行密码链接地址:{0}''',
        }),
    "online_configure":DotDict({
        "qmBZW":{
            "customer_service":u"官方QQ: 3050858895",
            "qq_group":u"官方QQ群: 431916936",
            "enable_speaker":True,
            "enable_game_chat":True,
            "enable_three_chat": True,
            "enable_turner": True,
            "store_words":u"活动期间, 金币充值买一送一!",
            "exclude_room_count":4,
            "enable_game_online_award":True,
            "enable_three_online_award":True,
            "enable_daily_charge_award":False,
            "enable_charge_double_award":True,
            "activity_coin_multiple":1,
            "enable_game_red_envelope":False,
            "enable_three_red_envelope":True,
            "enable_fruit_red_envelope":True,
            "enable_monkey_fifty_money_bags":False,
            "mall_money_bag_type":MoneyBagType.MONKEY_FIFTY_RMB_BAGS,
            "enable_gift_bag_exchange":True,
            "enable_lottery_exchange":True,
            "enable_bull_download":True,
            "not_baidu_check_mode":True,
            "fruit_enabled":False,
            "hundred_enabled":True,
            "turncard_enabled":True,
            "enable_activity":True,
            "enable_vip_treasure":True,
	        "not_channel_bull_download":['zx001','zx002','zx003','zx004','zx005_phone',
                'zx005_91','zx006','zx007','zx010','zx011','zx014','zx016','zx017',
                'zx020', '18_zhiyifu_', 'zx009', 'zx018', 'zx021', 'zx022', 'zx023',
                '7012431-88_zhiyifu_', 'lenovo_duowan', 'ledou', 'sj08', 'zx025', 'zx027', 'zx012']
            },
        }),
    'vip_titles':DotDict({
            Vip.NONE:u"普通玩家",
            Vip.NORMAL:u"白银VIP",
            Vip.GOLD:u"黄金VIP",
            Vip.DIAMOND:u"蓝钻VIP",
            Vip.CROWN:u"皇冠VIP",
            Vip.SUPREMACY:u"至尊VIP",
            }),
})