# -*- coding:utf-8 -*-

from go.util import DotDict
from card.core.property.three import Property
from card.core.enum import Vip

STORE = DotDict({
    'bull_url':'http://oss.holytree.com.cn/bull_andriod_v1.1.apk',
    'limited_item_count_key':'Item:limited_item_count_key{0}',
    'limited_item_pro':21.2,
    'sell_items':set([Property.RABBIT_GIRL, Property.ROSES, Property.SHIP,
                        Property.CAR, Property.ROSE, Property.CIGAR,
                        Property.RED_WINE,]), 
    'purchase_items':set([Property.NAME_CARD, Property.KICK_SEAT_CARD, 
                        Property.AVOID_KICK_CARD, Property.BAD_EGG,
                        Property.SOAP, Property.SPEAKER, Property.REPLACE_CARD,]),
    'charge_items':set([Property.TWO_RMB_COINS, Property.SIX_RMB_COINS,
                        Property.THIRTY_RMB_COINS, Property.FIFTH_RMB_COINS,
                        Property.HUNDRED_RMB_COINS, Property.THREE_HUNDRED_RMB_COINS,
                        Property.NEWBIE_COIN_BAG_ONE, Property.VIP_COIN_BAG,
                        Property.QUICK_FOUR_RMB_COINS,
                        Property.QUICK_SIX_RMB_COINS, Property.QUICK_EIGHT_RMB_COINS,
                        Property.REPLACE_CARD_BAGS, Property.KICK_SEAT_CARD_BAGS,
                        Property.BAD_EGG_BAGS, Property.AVOID_KICK_CARD_BAGS,
                        Property.SOAP_BAGS, Property.NEWBIE_PROPERTY_BAG_ONE,
                        Property.VIP_PROPERTY_BAG, Property.ONE_RMB_COINS,
                        Property.NEWBIE_TWO_RMB_COINS, Property.NEWYEAR_SIX_RMB_BAGS,
                        Property.MONKEY_FIFTY_RMB_BAGS, Property.EIGHT_HUNDRED_RMB_BAGS,
                        Property.LIMITED_GIFT_BAG,
                        Property.CAT_FOOD_GIFT_BAG,
                        Property.VIP_BAG_NORMAL,
                        Property.VIP_BAG_GOLD,
                        Property.VIP_BAG_DIAMOND,
                        Property.VIP_BAG_CROWN,
                        Property.VIP_BAG_SUPREMACY,
                        Property.SUPER_BAG,
                        ]),
    'item_names':{
            101: u'金币',
            201: u'兔女郎',
            202: u'高档别墅',
            203: u'豪华游轮',
            204: u'跑车',
            205: u'雪茄',
            206: u'红酒',
            409: u'免费翻牌卡',
            501: u'踢人卡',
            503: u'防踢卡',
            505: u'小喇叭',
            507: u'换牌卡',
            509: u'臭鸡蛋',
            511: u'改名卡',
            513: u'免费翻牌卡',
            514: u'肥皂',
            },
    'lobby_newbie_item':Property.NEWBIE_TWO_RMB_COINS,
    'newbie_charge_items':DotDict({
        'mmZFT':[Property.NEWBIE_COIN_BAG_ONE, 
                Property.ONE_RMB_COINS,
                Property.NEWBIE_PROPERTY_BAG_ONE,
                Property.NEWBIE_TWO_RMB_COINS, 
                Property.NEWYEAR_SIX_RMB_BAGS,
                Property.MONKEY_FIFTY_RMB_BAGS,
                Property.LIMITED_GIFT_BAG,
                Property.CAT_FOOD_GIFT_BAG,],
        'qmBZW':[Property.NEWBIE_COIN_BAG_ONE, 
                Property.ONE_RMB_COINS,
                Property.NEWBIE_PROPERTY_BAG_ONE,
                Property.NEWBIE_TWO_RMB_COINS, 
                Property.NEWYEAR_SIX_RMB_BAGS,
                Property.MONKEY_FIFTY_RMB_BAGS,
                Property.LIMITED_GIFT_BAG,
                Property.CAT_FOOD_GIFT_BAG,
                Property.VIP_BAG_NORMAL,
                Property.VIP_BAG_GOLD,
                Property.VIP_BAG_DIAMOND,
                Property.VIP_BAG_CROWN,
                Property.VIP_BAG_SUPREMACY,
                Property.SUPER_BAG
                 ],
        }),
    'weekly_charge_items':DotDict({
        'mmZFT':[Property.VIP_COIN_BAG, Property.VIP_PROPERTY_BAG,],
        'qmBZW':[Property.VIP_COIN_BAG, Property.VIP_PROPERTY_BAG,],
        }),
    'daily_charge':DotDict({
        'mmZFT':DotDict({
            'daily_items':[Property.KICK_SEAT_CARD_BAGS,  Property.AVOID_KICK_CARD_BAGS,],
            'daily_counts':DotDict({
                Property.KICK_SEAT_CARD_BAGS:DotDict({
                    Vip.NONE:0,
                    Vip.NORMAL:1,
                    Vip.GOLD:2,
                    Vip.DIAMOND:3,
                    Vip.CROWN:4,
                    Vip.SUPREMACY:4,
                    }),
                Property.AVOID_KICK_CARD_BAGS:DotDict({
                    Vip.NONE:0,
                    Vip.NORMAL:1,
                    Vip.GOLD:2,
                    Vip.DIAMOND:3,
                    Vip.CROWN:4,
                    Vip.SUPREMACY:4,
                    }),
                }),
            }),
        'qmBZW':DotDict({
            'daily_items':[Property.KICK_SEAT_CARD_BAGS,  Property.AVOID_KICK_CARD_BAGS,],
            'daily_counts':DotDict({
                Property.KICK_SEAT_CARD_BAGS:DotDict({
                    Vip.NONE:0,
                    Vip.NORMAL:1,
                    Vip.GOLD:2,
                    Vip.DIAMOND:3,
                    Vip.CROWN:4,
                    Vip.SUPREMACY:4,
                    }),
                Property.AVOID_KICK_CARD_BAGS:DotDict({
                    Vip.NONE:0,
                    Vip.NORMAL:1,
                    Vip.GOLD:2,
                    Vip.DIAMOND:3,
                    Vip.CROWN:4,
                    Vip.SUPREMACY:4,
                    }),
                }),
            }),
        }),
    'no_charge_items':DotDict({
        'mmZFT':[Property.NEWBIE_PROPERTY_BAG_ONE,],
        'qmBZW':[Property.NEWBIE_PROPERTY_BAG_ONE,],
        }),
    'monthly_payment_available': False,
    'limited_charge_items':DotDict({
        'mmZFT':DotDict({
            Property.LIMITED_GIFT_BAG:{'life_time':48 * 3600},
            }),
        'qmBZW':DotDict({
            Property.LIMITED_GIFT_BAG:{'life_time':48 * 3600},
            }),
        }),
})

