# -*- coding:utf-8 -*-

from go.util import DotDict
from card.core.enum import Vip
from card.core.property.three import Property

VIP = DotDict({
    'vip5_version':'1.8',
    'daily_awards':DotDict({
        Vip.NONE:[],
        Vip.NORMAL:[], 
        Vip.GOLD:[DotDict({'item_id':Property.REPLACE_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':0}),
                    DotDict({'item_id':Property.SOAP.item_id, 'count':0}),
                    ], 
        Vip.DIAMOND:[DotDict({'item_id':Property.REPLACE_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':0}),
                    DotDict({'item_id':Property.SOAP.item_id, 'count':0}),
                    ], 
        Vip.CROWN:[DotDict({'item_id':Property.REPLACE_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':0}),
                    DotDict({'item_id':Property.SOAP.item_id, 'count':0}),
                    ], 
        Vip.SUPREMACY:[DotDict({'item_id':Property.REPLACE_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':0}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':0}),
                    DotDict({'item_id':Property.SOAP.item_id, 'count':0}),
                    ], 
        }),
    'speaker_award':DotDict({
        Vip.NONE : DotDict({'item_id':Property.DAILY_SPEAKER.item_id, 'count':0}),
        Vip.NORMAL : DotDict({'item_id':Property.DAILY_SPEAKER.item_id, 'count':1}),
        Vip.GOLD : DotDict({'item_id':Property.DAILY_SPEAKER.item_id, 'count':2}),
        Vip.DIAMOND : DotDict({'item_id':Property.DAILY_SPEAKER.item_id, 'count':3}),
        Vip.CROWN : DotDict({'item_id':Property.DAILY_SPEAKER.item_id, 'count':4}),
        Vip.SUPREMACY : DotDict({'item_id':Property.DAILY_SPEAKER.item_id, 'count':5}),
        }),
    'vip_bags':DotDict({
        Vip.NONE:[],
        Vip.NORMAL:[DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':2}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':2}),
                    DotDict({'item_id':Property.SPEAKER.item_id, 'count':2}),
        ], 
        Vip.GOLD:[DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':6}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':6}),
                    DotDict({'item_id':Property.SPEAKER.item_id, 'count':6}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':6}),
                    ], 
        Vip.DIAMOND:[DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':12}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':12}),
                    DotDict({'item_id':Property.SPEAKER.item_id, 'count':12}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':12}),
                    DotDict({'item_id':Property.SOAP.item_id, 'count':12}),
                    ], 
        Vip.CROWN:[DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':32}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':32}),
                    DotDict({'item_id':Property.SPEAKER.item_id, 'count':32}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':32}),
                    DotDict({'item_id':Property.SOAP.item_id, 'count':32}),
                    ], 
        Vip.SUPREMACY:[DotDict({'item_id':Property.KICK_SEAT_CARD.item_id, 'count':32}),
                    DotDict({'item_id':Property.AVOID_KICK_CARD.item_id, 'count':32}),
                    DotDict({'item_id':Property.SPEAKER.item_id, 'count':32}),
                    DotDict({'item_id':Property.BAD_EGG.item_id, 'count':32}),
                    DotDict({'item_id':Property.SOAP.item_id, 'count':32}),
                    ], 
        }),
})
